server:
  port: 8081

spring:
  application:
    name: kafka-consumer
  datasource:
    url: jdbc:postgresql://localhost:5434/service_consumer
    username: consumer
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: service-b
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ostroverhov.kafka.consumer.model.EventMessage

app:
  topics:
    request: events.request
    response: events.response

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
